### ISSUE TITLE
SES6 beta compatibility

### ISSUE THREAD

**Issue by bwgartner** [dmbyte/benchmaster#34]
FYI, running these tests on pre-release version of upcoming SES6 release and found the following items which may need adjustment in the scripts (some are related to more minimal install approach of base SLE version):

- admin/salt master needs "bc", "fio" installed

- workload needs "screen", "fio" installed

Note: given fio particulars, the workload needs to have the same version as the admin, so would be good to cite it needs the same base SLE version for compatibility.

- had issues with rawavail/rawspace/allocunit calculations (perhaps due to changes in underlying ceph versions), so had to read comments, manually calculate and hardcode values into the script

- for some reason, the "prepare" invocation would not get ssh keys in place for the workload systems (so had to manually do that)

- each successive test seems to add another detached screen session and "clean" invocation didn't seem to consistently remove them

**Comment by dmbyte** [comment]
adding checks to install bc, fio.  need to investigate the others still.

**Comment by dmbyte** [comment]
fixed with ses6 branch
